## ASG Values
auto_scaling_group_name: vivek-asg1
launch_configuration_name: vivek-lc1
launch_template_name: viveklc
min_size: 1
max_size: 2
desired_capacity: 1
image_id: ami-05134c8ef96964280
instance_type: t2.micro
subnet_id: ['subnet-0f30c30418def6379', 'subnet-03ca36de9a927fe8e']
security_group_name: vivekWebAppSecurityGroup1
bucket_name: vivekbuckets3
vpc_id: vpc-0321f38a7b594180d
loadbalancer_name: vivekwebapp-lb1
lb_targetgroup: vivekwebapp-tg1
ec2_name: vivekwebserver1
sns_topic_name: viekdemo-sns
protocol: email
email_id: vcheruku98@gmail.com
subject: 'Test Alert'
message: 'This is a test alert for health issues'